### ISSUE TITLE
[feature request] Auto resize

### ISSUE THREAD

**Issue by Nerian** [bootstrap-wysiwyg/bootstrap3-wysiwyg#122]
Hi,

It would be awesome if the editor supported an option to autoresize itself when the contents are longer than the current height.

Looks like @simple10 implemented a solution:

https://github.com/simple10/bootstrap-wysihtml5-sass/commit/eb5ab6f0722349c6962be9ff823ff4e2f2cbc843

Perhaps this could be ported over this project?

**Comment by andrew-za** [comment]
I need this ... kind of pointless having a editor with a limited height???
