### ISSUE TITLE
Clearing the text-editor

### ISSUE THREAD

**Issue by chrifmarwen** [bootstrap-wysiwyg/bootstrap3-wysiwyg#140]
Is there a way to clear the contents of the textarea ? my intuition is to use $('.textarea').val(''); but this has not worked, neither has $('.textarea').empty() worked.

**Comment by davidwieler** [comment]
Did you resolve this? It's not working for me either, would love to know your solution.

**Comment by davidwieler** [comment]
Nevermind, I created a function that does stuff:

    <div class="textarea-fill"></div>
    function create_textarea(text){

        var text_fill = text || '';
        $('.textarea').remove()

        $('.textarea-fill').html('<textarea class="textarea" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px;" placeholder="Enter text ...">'+text_fill+'</textarea>')

        $('.textarea').wysihtml5({
          toolbar: {
            "fa": true,
            "font-styles": true, //Font styling, e.g. h1, h2, etc. Default true
            "emphasis": true, //Italics, bold, etc. Default true
            "lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
            "html": true, //Button which allows you to edit the generated HTML. Default false
            "link": true, //Button to insert a link. Default true
            "image": true, //Button to insert an image. Default true,
            "color": false, //Button to change color of font  
            "blockquote": true, //Blockquote  
            "size": 'sm' //default: none, other options are xs, sm, lg
          }
        }); 

     }
