### ISSUE TITLE
Link window modal

### ISSUE THREAD

**Issue by jonnydevv** [bootstrap-wysiwyg/bootstrap3-wysiwyg#165]
Hello!
How can i avoid link window from showing again. When i remove whitespace after link, link window modal shows again.

Thanks in advance

**Comment by ILunie** [comment]
https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/issues/104

**Comment by ILunie** [comment]
Follow this [thread](https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/issues/104)

**Comment by jonnydevv** [comment]
That's what i was looking for!
Thanks
