### ISSUE TITLE
[CLOSED] paste from MS Word results in HTML comments in the editor

### ISSUE THREAD

**Issue by Waxolunist** [bootstrap-wysiwyg/bootstrap3-wysiwyg#29]
<a href="https://github.com/iampivot"><img src="https://avatars.githubusercontent.com/u/1378266?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iampivot](https://github.com/iampivot)**
_Thursday Jan 16, 2014 at 13:09 GMT_
_Originally opened as https://github.com/Waxolunist/bootstrap3-wysihtml5-bower/issues/29_

---

When pasting in from MS Word, then the commented out formatting information that MS Word includes in the markup is added and made visible in the editor, eg like 

<!-- /\* Font Definitions */ @font-face {font ... etc.

This only happens in firefox and not in chrome, and it doesn't seem to happen in a 'pure' wysihtml5 setup, eg. at http://xing.github.io/wysihtml5/examples/advanced.html, so it must be related to how bootstrap-wysihtml5 configures the parser rules.

Problem also described here; http://stackoverflow.com/questions/15046225/wysihtml5-copying-text-from-a-word-document-to-the-editor

**Comment by drunkBottle6** [comment]
when i try to copy paste from ms.outlook and ms word
the result is show like this
[Image of the example](http://imgur.com/a/nbVrH)
any suggestion to fix this?
Thank you
