### ISSUE TITLE
[CLOSED] 'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach). 

### ISSUE THREAD

**Issue by Waxolunist** [bootstrap-wysiwyg/bootstrap3-wysiwyg#88]
<a href="https://github.com/canfiax"><img src="https://avatars.githubusercontent.com/u/3786627?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [canfiax](https://github.com/canfiax)**
_Monday Sep 08, 2014 at 19:58 GMT_
_Originally opened as https://github.com/Waxolunist/bootstrap3-wysihtml5-bower/issues/88_

---

What does this mean? Outputted in console.

`'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).`

**Comment by Roywcm** [comment]
I still have this issue with version 0.3.3
